config/routes.rb
Rails.application.routes.draw do

  resources :estabelecimentos
  resources :disciplinas
  resources :turmas
  scope path_names: { new: "novo", edit: "editar" } do
    resources :usuarios
  end
  
  root to: "usuarios#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/disciplina.rb
class Disciplina < ApplicationRecord
end

app/controllers/disciplinas_controller.rb
class DisciplinasController < ApplicationController
  before_action :set_disciplina, only: [:show, :edit, :update, :destroy]

  # GET /disciplinas
  def index
    @disciplinas = Disciplina.all
  end

  # GET /disciplinas/1
  def show
  end

  # GET /disciplinas/new
  def new
    @disciplina = Disciplina.new
  end

  # GET /disciplinas/1/edit
  def edit
  end

  # POST /disciplinas
  def create
    @disciplina = Disciplina.new(disciplina_params)

    if @disciplina.save
      redirect_to disciplinas_url, notice: t('messages.success.create', model: t('disciplina'), genero: 'a')
    else
      render :new
    end
  end

  # PATCH/PUT /disciplinas/1
  def update
    if @disciplina.update(disciplina_params)
      redirect_to disciplinas_url, notice: t('messages.success.update', model: t('disciplina'), genero: 'a')
    else
      render :edit
    end
  end

  # DELETE /disciplinas/1
  def destroy
    @disciplina.destroy
    redirect_to disciplinas_url, notice: t('messages.success.delete', model: t('disciplina'), genero: 'a')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disciplina
      @disciplina = Disciplina.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def disciplina_params
      params.require(:disciplina).permit(:nome, :codigo, :ativo)
    end
end

app/views/disciplinas/_form.html.erb
<%= form_with(model: disciplina, :html => { :class => "form-horizontal" }, local: true) do |form| %>
  <% if @disciplina.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <div class="alert-heading">
        <h3 class="alert-title"><%= pluralize(@disciplina.errors.count, t('error')) %> <%= pluralize_without_count(@disciplina.errors.count, t('found')) %>:</h3>
      </div>
      <div class="alert-body">
        <ul>
        <% @disciplina.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nome, t('nome') %>
    <%= form.text_field :nome, id: :disciplina_nome, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :codigo, t('codigo') %>
    <%= form.text_field :codigo, id: :disciplina_codigo, :class => "form-control" %>
  </div>

  <div class="form-check">
    <%= form.check_box :ativo, id: :disciplina_ativo, :class => "form-check-input" %>
    <%= form.label :ativo, t('ativo'), :class => "form-check-label" %>
  </div>

  <div class="form-group mt-2">
    <%= form.submit t('.save', :default => t('helpers.links.save')), :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t('helpers.links.cancel')),
      disciplinas_path, :class => 'btn btn-secondary' %>
  </div>
<% end %>

app/views/disciplinas/edit.html.erb
<% content_for :titulo do %>
  <%= t('.title', :default => :'helpers.titles.edit', :model => t('disciplina')) %>
<% end %>

<%= render 'form', disciplina: @disciplina %>

app/views/disciplinas/index.html.erb
<% content_for :titulo do %>
  <%= t('.title', :default =>  t('helpers.titles.list'), :model => t('disciplina').pluralize) %>
<% end %>

<table class="table table-sm table-hover table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col" class="text-center">#</th>
      <th scope="col"><%= t('nome') %></th>
      <th scope="col"><%= t('codigo') %></th>
      <th scope="col"><%= t('ativo') %></th>
      <th scope="col" class="text-center"><%= t('.actions', :default => t('helpers.actions')) %></th>
    </tr>
  </thead>
  <tbody>
    <% @disciplinas.each do |disciplina| %>
      <tr>
        <th scope="col" class="text-center"><%= disciplina.id %></th>
        <td><%= disciplina.nome %></td>
        <td><%= disciplina.codigo %></td>
        <td><i class="fas fa<%= '-check' if disciplina.ativo == true %>-square"></i></td>
        <td class="acoes">
        <%= link_to disciplina,
          :title => t('helpers.links.show'),
          :class => 'btn btn-info btn-xs' do %>
          <i class="fas fa-search"></i>
        <% end %>
        <%= link_to edit_disciplina_path(disciplina),
          :title => t('helpers.links.edit'),
          :class => 'btn btn-success btn-xs' do %>
          <i class="fas fa-edit"></i>
        <% end %>
        <a data-toggle="modal" data-target="#modalExcluir"
          data-href="<%= disciplina_path(disciplina) %>"
          class="btn btn-danger btn-xs text-white"
          title="<%= t('helpers.links.delete') %>">
          <i class="far fa-trash-alt"></i>
        </a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to new_disciplina_path,
  :class => 'btn btn-primary' do %>
  <i class="fas fa-plus"></i>
  <%= t('helpers.links.new') %>
<% end %>

app/views/disciplinas/new.html.erb
<% content_for :titulo do %>
  <%= t('.title', :default => :'helpers.titles.new', :model => t('disciplina')) %>
<% end %>

<%= render 'form', disciplina: @disciplina %>

app/views/disciplinas/show.html.erb
<% content_for :titulo do %>
  <%= t('.title', :default => :'helpers.titles.show', :model => t('disciplina')) %>
<% end %>

<dl class="dl-horizontal">
  <p>
    <dt><strong>Nome:</strong></dt>
    <dd><%= @disciplina.nome %></dd>
  </p>
  <p>
    <dt><strong>Codigo:</strong></dt>
    <dd><%= @disciplina.codigo %></dd>
  </p>
  <p>
    <dt><strong>Ativo:</strong></dt>
    <dd><%= @disciplina.ativo %></dd>
  </p>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              disciplinas_path, :class => 'btn btn-secondary'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_disciplina_path(@disciplina), :class => 'btn btn-primary' %>
<%= link_to t('.delete', :default => t("helpers.links.delete")),
              disciplina_path(@disciplina),
              :method => 'delete', :class => 'btn btn-danger',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm_delete", :default => 'Você tem certeza que deseja excluir?')) }%>