config/routes.rb
Rails.application.routes.draw do

  resources :estabelecimentos
  resources :disciplinas
  resources :turmas
  scope path_names: { new: "novo", edit: "editar" } do
    resources :usuarios
  end
  
  root to: "usuarios#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/turma.rb
class Turma < ApplicationRecord
end

app/controllers/turmas_controller.rb
class TurmasController < ApplicationController
  before_action :set_turma, only: [:show, :edit, :update, :destroy]

  # GET /turmas
  def index
    @turmas = Turma.all
  end

  # GET /turmas/1
  def show
  end

  # GET /turmas/new
  def new
    @turma = Turma.new
  end

  # GET /turmas/1/edit
  def edit
  end

  # POST /turmas
  def create
    @turma = Turma.new(turma_params)

    if @turma.save
      redirect_to turmas_url, notice: t('messages.success.create', model: t('turma'), genero: 'a')
    else
      render :new
    end
  end

  # PATCH/PUT /turmas/1
  def update
    if @turma.update(turma_params)
      redirect_to turmas_url, notice: t('messages.success.update', model: t('turma'), genero: 'a')
    else
      render :edit
    end
  end

  # DELETE /turmas/1
  def destroy
    @turma.destroy
    redirect_to turmas_url, notice: t('messages.success.delete', model: t('turma'), genero: 'a')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turma
      @turma = Turma.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def turma_params
      params.require(:turma).permit(:nome, :codigo, :ativo)
    end
end

app/views/turmas/_form.html.erb
<%= form_with(model: turma, :html => { :class => "form-horizontal" }, local: true) do |form| %>
  <% if @turma.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <div class="alert-heading">
        <h3 class="alert-title"><%= pluralize(@turma.errors.count, t('error')) %> <%= pluralize_without_count(@turma.errors.count, t('found')) %>:</h3>
      </div>
      <div class="alert-body">
        <ul>
        <% @turma.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nome, t('nome') %>
    <%= form.text_field :nome, id: :turma_nome, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :codigo, t('codigo') %>
    <%= form.text_field :codigo, id: :turma_codigo, :class => "form-control" %>
  </div>

  <div class="form-check">
    <%= form.check_box :ativo, id: :turma_ativo, :class => "form-check-input" %>
    <%= form.label :ativo, t('ativo'), :class => "form-check-label" %>
  </div>

  <div class="form-group mt-2">
    <%= form.submit t('.save', :default => t('helpers.links.save')), :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t('helpers.links.cancel')),
      turmas_path, :class => 'btn btn-secondary' %>
  </div>
<% end %>

app/views/turmas/edit.html.erb
<% content_for :titulo do %>
  <%= t('.title', :default => :'helpers.titles.edit', :model => t('turma')) %>
<% end %>

<%= render 'form', turma: @turma %>

app/views/turmas/index.html.erb
<% content_for :titulo do %>
  <%= t('.title', :default =>  t('helpers.titles.list'), :model => t('turma').pluralize) %>
<% end %>

<table class="table table-sm table-hover table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col" class="text-center">#</th>
      <th scope="col"><%= t('nome') %></th>
      <th scope="col"><%= t('codigo') %></th>
      <th scope="col"><%= t('ativo') %></th>
      <th scope="col" class="text-center"><%= t('.actions', :default => t('helpers.actions')) %></th>
    </tr>
  </thead>
  <tbody>
    <% @turmas.each do |turma| %>
      <tr>
        <th scope="col" class="text-center"><%= turma.id %></th>
        <td><%= turma.nome %></td>
        <td><%= turma.codigo %></td>
        <td><i class="fas fa<%= '-check' if turma.ativo == true %>-square"></i></td>
        <td class="acoes">
        <%= link_to turma,
          :title => t('helpers.links.show'),
          :class => 'btn btn-info btn-xs' do %>
          <i class="fas fa-search"></i>
        <% end %>
        <%= link_to edit_turma_path(turma),
          :title => t('helpers.links.edit'),
          :class => 'btn btn-success btn-xs' do %>
          <i class="fas fa-edit"></i>
        <% end %>
        <a data-toggle="modal" data-target="#modalExcluir"
          data-href="<%= turma_path(turma) %>"
          class="btn btn-danger btn-xs text-white"
          title="<%= t('helpers.links.delete') %>">
          <i class="far fa-trash-alt"></i>
        </a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to new_turma_path,
  :class => 'btn btn-primary' do %>
  <i class="fas fa-plus"></i>
  <%= t('helpers.links.new') %>
<% end %>

app/views/turmas/new.html.erb
<% content_for :titulo do %>
  <%= t('.title', :default => :'helpers.titles.new', :model => t('turma')) %>
<% end %>

<%= render 'form', turma: @turma %>

app/views/turmas/show.html.erb
<% content_for :titulo do %>
  <%= t('.title', :default => :'helpers.titles.show', :model => t('turma')) %>
<% end %>

<dl class="dl-horizontal">
  <p>
    <dt><strong>Nome:</strong></dt>
    <dd><%= @turma.nome %></dd>
  </p>
  <p>
    <dt><strong>Codigo:</strong></dt>
    <dd><%= @turma.codigo %></dd>
  </p>
  <p>
    <dt><strong>Ativo:</strong></dt>
    <dd><%= @turma.ativo %></dd>
  </p>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              turmas_path, :class => 'btn btn-secondary'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_turma_path(@turma), :class => 'btn btn-primary' %>
<%= link_to t('.delete', :default => t("helpers.links.delete")),
              turma_path(@turma),
              :method => 'delete', :class => 'btn btn-danger',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm_delete", :default => 'Você tem certeza que deseja excluir?')) }%>