config/routes.rb
Rails.application.routes.draw do

  resources :estabelecimentos
  resources :disciplinas
  resources :turmas
  scope path_names: { new: "novo", edit: "editar" } do
    resources :usuarios
  end
  
  root to: "usuarios#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_secure_password
  validates :nome, presence: true
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  def index
    @usuarios = Usuario.order(:nome, email: :desc)
  end

  # GET /usuarios/1
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  def create
    @usuario = Usuario.new(usuario_params)

    if @usuario.save
      redirect_to usuarios_url, notice: t('messages.success.create', model: t('usuario'), genero: 'o')
    else
      render :new
    end
  end

  # PATCH/PUT /usuarios/1
  def update
    if @usuario.update(usuario_params)
      redirect_to usuarios_url, notice: t('messages.success.update', model: t('usuario'), genero: 'o')
    else
      render :edit
    end
  end

  # DELETE /usuarios/1
  def destroy
    @usuario.destroy
    redirect_to usuarios_url, notice: t('messages.success.delete', model: t('usuario'), genero: 'o')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def usuario_params
      params.require(:usuario).permit(:nome, :email, :password, :password_confirmation, :ativo)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, :html => { :class => "form-horizontal" }, local: true) do |form| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <div class="alert-heading">
        <h3 class="alert-title"><%= pluralize_with_count(@usuario.errors.count, t('error')) %>:</h3>
      </div>
      <div class="alert-body">
        <ul>
        <% @usuario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nome, t('nome') %>
    <%= form.text_field :nome, id: :usuario_nome, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email, t('email') %>
    <%= form.text_field :email, id: :usuario_email, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password, t('password') %>
    <%= form.password_field :password, id: :usuario_password, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :password_confirmation, t('password_confirmation') %>
    <%= form.password_field :password_confirmation, id: :usuario_password_confirmation, :class => "form-control" %>
  </div>

  <div class="form-check">
    <%= form.check_box :ativo, id: :usuario_ativo, :class => "form-check-input" %>
    <%= form.label :ativo, t('ativo'), :class => "form-check-label" %>
  </div>

  <div class="form-group mt-2">
    <%= form.submit t('.save', :default => t('helpers.links.save')), :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t('helpers.links.cancel')),
      usuarios_path, :class => 'btn btn-secondary' %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<% content_for :titulo do %>
  <%= t('.title', :default => :'helpers.titles.edit', :model => t('usuario')) %>
<% end %>

<%= render 'form', usuario: @usuario %>

app/views/usuarios/index.html.erb
<% content_for :titulo do %>
  <%= t('.title', :default =>  t('helpers.titles.list'), :model => t('usuario').pluralize) %>
<% end %>

<table class="table table-sm table-hover table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col" class="text-center">#</th>
      <th scope="col"><%= t('nome') %></th>
      <th scope="col"><%= t('email') %></th>
      <th scope="col"><%= t('ativo') %></th>
      <th scope="col" class="text-center"><%= t('.actions', :default => t('helpers.actions')) %></th>
    </tr>
  </thead>
  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <th scope="col" class="text-center"><%= usuario.id %></th>
        <td><%= usuario.nome %></td>
        <td><%= usuario.email %></td>
        <td><i class="fas fa<%= '-check' if usuario.ativo == true %>-square"></i></td>
        <td class="acoes">
        <%= link_to usuario,
          :title => t('helpers.links.show'),
          :class => 'btn btn-info btn-xs' do %>
          <i class="fas fa-search"></i>
        <% end %>
        <%= link_to edit_usuario_path(usuario),
          :title => t('helpers.links.edit'),
          :class => 'btn btn-success btn-xs' do %>
          <i class="fas fa-edit"></i>
        <% end %>
        <a data-toggle="modal" data-target="#modalExcluir"
          data-href="<%= usuario_path(usuario) %>"
          class="btn btn-danger btn-xs text-white"
          title="<%= t('helpers.links.delete') %>">
          <i class="far fa-trash-alt"></i>
        </a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to new_usuario_path,
  :class => 'btn btn-primary' do %>
  <i class="fas fa-plus"></i>
  <%= t('helpers.links.new') %>
<% end %>

app/views/usuarios/new.html.erb
<% content_for :titulo do %>
  <%= t('.title', :default => :'helpers.titles.new', :model => t('usuario')) %>
<% end %>

<%= render 'form', usuario: @usuario %>

app/views/usuarios/show.html.erb
<% content_for :titulo do %>
  <%= t('.title', :default => :'helpers.titles.show', :model => t('usuario')) %>
<% end %>

<dl class="dl-horizontal">
  <p>
    <dt><strong>Nome:</strong></dt>
    <dd><%= @usuario.nome %></dd>
  </p>
  <p>
    <dt><strong>Email:</strong></dt>
    <dd><%= @usuario.email %></dd>
  </p>
  <p>
    <dt><strong>Ativo:</strong></dt>
    <dd><%= @usuario.ativo %></dd>
  </p>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              usuarios_path, :class => 'btn btn-secondary'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_usuario_path(@usuario), :class => 'btn btn-primary' %>
<%= link_to t('.delete', :default => t("helpers.links.delete")),
              usuario_path(@usuario),
              :method => 'delete', :class => 'btn btn-danger',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm_delete", :default => 'Você tem certeza que deseja excluir?')) }%>