config/routes.rb
Rails.application.routes.draw do

  resources :estabelecimentos
  resources :disciplinas
  resources :turmas
  scope path_names: { new: "novo", edit: "editar" } do
    resources :usuarios
  end
  
  root to: "usuarios#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/estabelecimento.rb
class Estabelecimento < ApplicationRecord
end

app/controllers/estabelecimentos_controller.rb
class EstabelecimentosController < ApplicationController
  before_action :set_estabelecimento, only: [:show, :edit, :update, :destroy]

  # GET /estabelecimentos
  def index
    @estabelecimentos = Estabelecimento.all
  end

  # GET /estabelecimentos/1
  def show
  end

  # GET /estabelecimentos/new
  def new
    @estabelecimento = Estabelecimento.new
  end

  # GET /estabelecimentos/1/edit
  def edit
  end

  # POST /estabelecimentos
  def create
    @estabelecimento = Estabelecimento.new(estabelecimento_params)

    if @estabelecimento.save
      redirect_to estabelecimentos_url, notice: t('messages.success.create', model: t('estabelecimento'), genero: 'o')
    else
      render :new
    end
  end

  # PATCH/PUT /estabelecimentos/1
  def update
    if @estabelecimento.update(estabelecimento_params)
      redirect_to estabelecimentos_url, notice: t('messages.success.update', model: t('estabelecimento'), genero: 'o')
    else
      render :edit
    end
  end

  # DELETE /estabelecimentos/1
  def destroy
    @estabelecimento.destroy
    redirect_to estabelecimentos_url, notice: t('messages.success.delete', model: t('estabelecimento'), genero: 'o')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estabelecimento
      @estabelecimento = Estabelecimento.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def estabelecimento_params
      params.require(:estabelecimento).permit(:nome, :endereco, :ativo)
    end
end

app/views/estabelecimentos/_form.html.erb
<%= form_with(model: estabelecimento, :html => { :class => "form-horizontal" }, local: true) do |form| %>
  <% if @estabelecimento.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <div class="alert-heading">
        <h3 class="alert-title"><%= pluralize(@estabelecimento.errors.count, t('error')) %> <%= pluralize_without_count(@estabelecimento.errors.count, t('found')) %>:</h3>
      </div>
      <div class="alert-body">
        <ul>
        <% @estabelecimento.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nome, t('nome') %>
    <%= form.text_field :nome, id: :estabelecimento_nome, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :endereco, t('endereco') %>
    <%= form.text_field :endereco, id: :estabelecimento_endereco, :class => "form-control" %>
  </div>

  <div class="form-check">
    <%= form.check_box :ativo, id: :estabelecimento_ativo, :class => "form-check-input" %>
    <%= form.label :ativo, t('ativo'), :class => "form-check-label" %>
  </div>

  <div class="form-group mt-2">
    <%= form.submit t('.save', :default => t('helpers.links.save')), :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t('helpers.links.cancel')),
      estabelecimentos_path, :class => 'btn btn-secondary' %>
  </div>
<% end %>

app/views/estabelecimentos/edit.html.erb
<% content_for :titulo do %>
  <%= t('.title', :default => :'helpers.titles.edit', :model => t('estabelecimento')) %>
<% end %>

<%= render 'form', estabelecimento: @estabelecimento %>

app/views/estabelecimentos/index.html.erb
<% content_for :titulo do %>
  <%= t('.title', :default =>  t('helpers.titles.list'), :model => t('estabelecimento').pluralize) %>
<% end %>

<table class="table table-sm table-hover table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col" class="text-center">#</th>
      <th scope="col"><%= t('nome') %></th>
      <th scope="col"><%= t('endereco') %></th>
      <th scope="col"><%= t('ativo') %></th>
      <th scope="col" class="text-center"><%= t('.actions', :default => t('helpers.actions')) %></th>
    </tr>
  </thead>
  <tbody>
    <% @estabelecimentos.each do |estabelecimento| %>
      <tr>
        <th scope="col" class="text-center"><%= estabelecimento.id %></th>
        <td><%= estabelecimento.nome %></td>
        <td><%= estabelecimento.endereco %></td>
        <td><i class="fas fa<%= '-check' if estabelecimento.ativo == true %>-square"></i></td>
        <td class="acoes">
        <%= link_to estabelecimento,
          :title => t('helpers.links.show'),
          :class => 'btn btn-info btn-xs' do %>
          <i class="fas fa-search"></i>
        <% end %>
        <%= link_to edit_estabelecimento_path(estabelecimento),
          :title => t('helpers.links.edit'),
          :class => 'btn btn-success btn-xs' do %>
          <i class="fas fa-edit"></i>
        <% end %>
        <a data-toggle="modal" data-target="#modalExcluir"
          data-href="<%= estabelecimento_path(estabelecimento) %>"
          class="btn btn-danger btn-xs text-white"
          title="<%= t('helpers.links.delete') %>">
          <i class="far fa-trash-alt"></i>
        </a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to new_estabelecimento_path,
  :class => 'btn btn-primary' do %>
  <i class="fas fa-plus"></i>
  <%= t('helpers.links.new') %>
<% end %>

app/views/estabelecimentos/new.html.erb
<% content_for :titulo do %>
  <%= t('.title', :default => :'helpers.titles.new', :model => t('estabelecimento')) %>
<% end %>

<%= render 'form', estabelecimento: @estabelecimento %>

app/views/estabelecimentos/show.html.erb
<% content_for :titulo do %>
  <%= t('.title', :default => :'helpers.titles.show', :model => t('estabelecimento')) %>
<% end %>

<dl class="dl-horizontal">
  <p>
    <dt><strong>Nome:</strong></dt>
    <dd><%= @estabelecimento.nome %></dd>
  </p>
  <p>
    <dt><strong>Endereco:</strong></dt>
    <dd><%= @estabelecimento.endereco %></dd>
  </p>
  <p>
    <dt><strong>Ativo:</strong></dt>
    <dd><%= @estabelecimento.ativo %></dd>
  </p>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              estabelecimentos_path, :class => 'btn btn-secondary'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_estabelecimento_path(@estabelecimento), :class => 'btn btn-primary' %>
<%= link_to t('.delete', :default => t("helpers.links.delete")),
              estabelecimento_path(@estabelecimento),
              :method => 'delete', :class => 'btn btn-danger',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm_delete", :default => 'Você tem certeza que deseja excluir?')) }%>